export const COLUMN_CARD_DROPPED = "COLUMN#CARD_DROPPED";
export const COLUMN_CARD_ADDED = "COLUMN#CARD_ADDED";
export const CARD_DRAG_STARTED = "CARD#DRAG_STARTED";
export const CARD_DRAGGED_OVER = "CARD#DRAGGED_OVER";
export const CARD_DRAG_ENDED = "CARD#DRAG_ENDED";
export const CARD_EDIT_TRIGGERED = "CARD#EDIT_TRIGGERED";
export const MODAL_CLOSED = "MODAL#CLOSED";
export const BOARD_COLUMN_ADDED = "BOARD#COLUMN_ADDED";
